name: snif
version: 1.2.3
description: >-
  Have you been turned into a newt?  Would you like to be?
  This package can help. It has all of the
  newt-transmogrification functionality you have been looking
  for.
homepage: https://example-pet-store.com/newtify
documentation: https://example-pet-store.com/newtify/docs
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  http: ^0.12.2
  meta: ^1.2.3
dev_dependencies:
  test: '>=1.15.0 <2.0.0'







